### ISSUE TITLE
No longer compatible with PropTypes

### ISSUE THREAD

**Issue by magic-m-johnson** [batata-frita/lekplats#7]
I just get a white screen in the edit-window. Probably due to changes in the accessibility of the PropTypes. 

You can fix this by simply adding [properTypes](https://github.com/magic-m-johnson/proper-types) support. ;)

![image](https://user-images.githubusercontent.com/27994580/40001676-0be4bde0-578f-11e8-8afa-620992015c40.png)

**Comment by Deschtex** [comment]
Closed by #8
